apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: my-flask-app
  ports:
  - protocol: TCP
    targetPort: {{ .Values.appPort }}
    port: 80