version: "3.7"
services:
  db:
     image: mysql:8.0
     volumes:
       - ./mydb:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: pythoncourse
       MYSQL_DATABASE: mydb
       MYSQL_USER: user
     ports:
       - "3306:3306"
     expose:
       - "3306"
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

  devops-rest:
    depends_on:
      - db
    image: ofirzvishaboo/flask_name_api:latest
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      MYSQL_DB_HOST: db:3306
      MYSQL_DB_USER: root
      MYSQL_DB_PASSWORD: pythoncourse
#    healthcheck:
#      test:  curl --fail http://localhost:5000/users/1 || exit 1
#      interval: 10s
#      timeout: 5s
#      retries: 5

volumes:
    mydb:





